---
title: "Dongsha Migrate Analysis"
output: html_notebook
---

Here is code that I used to set up migrate analyses on datasets from Dongsha atoll. These data are from samples that were collected by Rob Toonen, Michelle Gaither, Vanson Liu and Hawis Maduppa. The data themselves were largely generated by students in the BIO 444 class, and these students also set up the initial migrate runs for their class project. To do so they downloaded data from their species from GeOMe and picked 4-5 closest populations and set up several hypotheses about the best metapopulation model. I am now just taking those runs and re-running them twice more as migrate does not always converge well on a marginal likelihood for a model.

At first 

# Setting up the runs

At first I was just going to set up a screen for each run and run them all manually, but decided to write a script to rename the parmfiles uniformly. It finds files with the word "Parmfile" in them and then renames them to "parmfile"
```{bash parmfile_namer.sh}
#!
for d in */
        do
          cd $d
          echo $d
                for f in $(find ./ -maxdepth 1 -type f -exec grep -l 'Parmfile' {} \;)
                 do 
                         mv $f parmfile
                 done
          cd ..
        done  
 

```

I then deleted all the PDF outfiles from the directories to mark each directory as new (I had copied directories with finished analyses)
```{bash}
 find . -type f -iname "*.pdf" -delete
```

I used the following script to automagically set up a screen and run migrate in each sub-directory
```{bash screen_migrate.sh}
#!
#for s in */
#do
#       cd $s

        for m in */
        do
                cd $m
                echo $m
                screen -d -m migrate-n
                cd ..
        done
#       cd ..
#done
```

So now "Round 2" of these runs is off and running. I'll wait a week to check in and start round 3.

8/23/18

Finished Round 3

Rename outfiles like so
```{bash}
#!
for d in */
        do
          cd $d
          echo $d
                for f in $(find ./ -maxdepth 1 -type f -exec grep -l 'Options in use' {} \;)
                 do 
                         mv $f outfile.txt
                 done
          cd ..
        done  
  
#And wrap that up in a loop

M053-303-26932:dongsha1 cran5048$ for e in */
> do
> cd $e
> echo $e
> bash ../../outfile_renamer.sh
> cd ..
> done

```

