#does not work
#install.packages("poppr","adegenet","ape","ggplot2","mmod","magrittr","dplyr","treemap","pegas","hierfstat","seqinr","strataG","gdistance","ecodist","reshape2","ggplot2","WriteXLS","knitr", dependencies = T)

install.packages("poppr",dependencies = T)
install.packages("adegenet",dependencies = T)
install.packages("ape",dependencies = T)
install.packages("ggplot2",dependencies = T)
install.packages("mmod",dependencies = T)
install.packages("magrittr",dependencies = T)
install.packages("dplyr",dependencies = T)
install.packages("treemap",dependencies = T)
install.packages("pegas",dependencies = T)
install.packages("hierfstat",dependencies = T)
install.packages("seqinr",dependencies = T)
install.packages("strataG",dependencies = T)
install.packages("gdistance",dependencies = T)
install.packages("ecodist",dependencies = T)
install.packages("reshape2",dependencies = T)
install.packages("WriteXLS",dependencies = T)
install.packages("knitr",dependencies = T)
install.packages("devtools", dependencies = T)
install.packages("expm", dependencies = T)
install.packages("rentrez", dependencies = T)
install.packages("Hardy")
install.packages("ggmcmc", dependencies = T)
install_github("bjcochrane/TeachingPopGen", force = TRUE)
library(devtools)
library(ggplot2)
library(expm)
library(ape)
library(pegas)
library(strataG)
library(knitr)
library(rentrez)
library(stringr)
library(raster)
library(TeachingPopGen)


